CREATE DATABASE chat;

USE chat;

CREATE TABLE users (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, 
  username VARCHAR(255)
);

CREATE TABLE messages (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  text VARCHAR(255),
  createdAt DATETIME,
  user_id INT,
  roomname VARCHAR(255),
  FOREIGN KEY (user_id) REFERENCES users(id)
);